wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.3
    cli_version: 0.17.2
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1728203539
    t:
      1:
      - 1
      - 41
      - 49
      - 55
      - 63
      2:
      - 1
      - 5
      - 41
      - 49
      - 53
      - 55
      - 63
      3:
      - 2
      - 13
      - 16
      - 23
      - 61
      4: 3.12.3
      5: 0.17.2
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
